version: "3"


services:
  database:
    image: postgres
    restart: always
    volumes:
      - ../.volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: C9ERGFWJs2XjDM

  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080

networks:
  default:
    external:
      name: challenge_s2