version: '3'
services:
  web:
    build: site
    container_name: challenge_s2_dev
    ports :
     - 6005:80
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres
    restart: always
    volumes:
      - ./.volumes/dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: esgi-dev
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: sfdgfGHKGJFfkjfuir

  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080