version: '3'
services:
  web:
    build: ./.docker/site
    restart: "always"
    ports :
     - 6005:80
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - composer

  composer:
    build: ./.docker/composer
    volumes:
      - ./www:/app
    command: install --optimize-autoloader --ignore-platform-reqs
    restart: "no"

  maildev:
      image: maildev/maildev
      container_name: progMail
      command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
      ports:
        - "1080:80"
        - "26:25"
      restart: always

networks:
  default:
      name: challenge-s2
      external: true