version: '3'
services:
  web:
    build: site
    ports :
     - 6005:80
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - composer

  composer:
    build: ./.docker/composer
    volumes:
      - ./www:/app
    command: install --optimize-autoloader
    restart: "no"

networks:
  default:
    external:
      name: challenge-s2