name: deploy to preprod

on:
  push:
    branches:
      - feature/ci_cd


jobs:
  preprod:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: appleboy/scp-action@v0.1.3
        env:
          HOST: ${{ secrets.SSH_SERVER }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "/root/challenge/preprod"

      - name: restart docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd "/root/challenge/preprod" && docker compose -f docker-compose.dev.yml down && docker compose -f docker-compose.dev.yml up -d --build
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: run commands in container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker exec challenge_s2_dev composer install --no-dev --optimize-autoloader && docker exec challenge_s2_dev
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
