name: deploy to prod

on:
  push:
    branches:
      - main


jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: appleboy/scp-action@v0.1.3
        env:
          HOST: ${{ secrets.SSH_SERVER }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "/root/challenge/prod"

      - name: restart project
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd "/root/challenge/prod" && docker compose -f docker-compose.yml down && docker compose -f docker-compose.yml up -d --build
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
