name: deploy to prod

on:
  push:
    branches:
      - main


jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: 📂 Sync docker files
        uses: appleboy/scp-action@v0.1.3
        env:
          HOST: ${{ secrets.SSH_SERVER }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./docker-compose.global.yml"
          target: "/root/challenge"

      - name: 📂 Sync code files
        uses: appleboy/scp-action@v0.1.3
        env:
          HOST: ${{ secrets.SSH_SERVER }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "/root/challenge/prod"

      - name: delete docker files on project
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd "/root/challenge/prod" && rm docker-compose.dev.yml docker-compose.global.yml
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: restart global containers
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd "/root/challenge" && docker compose -f docker-compose.global.yml down --remove-orphans && docker compose -f docker-compose.global.yml up -d --build
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: restart project containers
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: cd "/root/challenge/prod" && docker compose -f docker-compose.yml down --remove-orphans && docker compose -f docker-compose.yml up -d --build
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}